### PR TITLE
Shutdown PHP after a queue timeout

### LINKED ISSUE #24: Queue timeouts should trigger `failed()` call
When a queued jobs run longer and times out we should:

- [x] Ensure that `$job->failed()` is called (via #31)
- [x] Close the database connection

### PR DESCRIPTION
**Pull request by georgeboot**
Fixes  #24

This will shutdown PHP (and with it, the lambda container instance) so that database connections and other sockets/handles will be closed.

### CODE REVIEW

File: src/Queue/Worker.php [hunk 1]
```diff
@@ -27,6 +27,9 @@ public function runSqsJob(Job $job, string $connectionName, WorkerOptions $optio
                 $job,
                 $this->maxAttemptsExceededException($job),
             );
+
+            // exit so that PHP will shutdown and close DB connections etc.
+            exit(1);
```
Comment (georgeboot) [inline src/Queue/Worker.php:32]: This is after the job has been "failed" and thus the job has already been released back to SQS and it _should_ also have been added to the `failed_job` table.

**Review by tillkruss — APPROVED** [review]
